/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatusRouteImport } from './routes/status'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as RecorderRouteImport } from './routes/recorder'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as CodeRouteImport } from './routes/$code'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ApiWikiRouteImport } from './routes/api/wiki'
import { Route as ApiLlmsDotjsonRouteImport } from './routes/api/llms[.]json'
import { Route as AuthedSpacesIndexRouteImport } from './routes/_authed/spaces/index'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as ApiWhiteboardSnapshotRouteImport } from './routes/api/whiteboard/snapshot'
import { Route as ApiWhiteboardPdfUploadRouteImport } from './routes/api/whiteboard/pdf-upload'
import { Route as ApiWbAssetsSplatRouteImport } from './routes/api/wb-assets/$'
import { Route as ApiMeetingsLeaveRouteImport } from './routes/api/meetings/leave'
import { Route as ApiLivekitWebhookRouteImport } from './routes/api/livekit/webhook'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing/webhook'
import { Route as ApiBillingPortalRouteImport } from './routes/api/billing/portal'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiAiAssistantRouteImport } from './routes/api/ai/assistant'
import { Route as AuthedSpacesSpaceIdRouteImport } from './routes/_authed/spaces/$spaceId'
import { Route as AuthedDashboardCodeRouteImport } from './routes/_authed/dashboard/$code'
import { Route as ApiAuthCallbackGoogleLinkRouteImport } from './routes/api/auth/callback/google-link'
import { Route as ApiAuthCallbackGoogleRouteImport } from './routes/api/auth/callback/google'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/verify.lazy').then((d) => d.Route))
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/terms.lazy').then((d) => d.Route))
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/status.lazy').then((d) => d.Route))
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/refund.lazy').then((d) => d.Route))
const RecorderRoute = RecorderRouteImport.update({
  id: '/recorder',
  path: '/recorder',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/recorder.lazy').then((d) => d.Route))
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/privacy.lazy').then((d) => d.Route))
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/pricing.lazy').then((d) => d.Route))
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth.lazy').then((d) => d.Route))
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/_authed.lazy').then((d) => d.Route))
const CodeRoute = CodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/$code.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/invite.$token.lazy').then((d) => d.Route))
const ApiWikiRoute = ApiWikiRouteImport.update({
  id: '/api/wiki',
  path: '/api/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmsDotjsonRoute = ApiLlmsDotjsonRouteImport.update({
  id: '/api/llms.json',
  path: '/api/llms.json',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSpacesIndexRoute = AuthedSpacesIndexRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/spaces/index.lazy').then((d) => d.Route),
)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/settings/index.lazy').then((d) => d.Route),
)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/dashboard/index.lazy').then((d) => d.Route),
)
const ApiWhiteboardSnapshotRoute = ApiWhiteboardSnapshotRouteImport.update({
  id: '/api/whiteboard/snapshot',
  path: '/api/whiteboard/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhiteboardPdfUploadRoute = ApiWhiteboardPdfUploadRouteImport.update({
  id: '/api/whiteboard/pdf-upload',
  path: '/api/whiteboard/pdf-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWbAssetsSplatRoute = ApiWbAssetsSplatRouteImport.update({
  id: '/api/wb-assets/$',
  path: '/api/wb-assets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsLeaveRoute = ApiMeetingsLeaveRouteImport.update({
  id: '/api/meetings/leave',
  path: '/api/meetings/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLivekitWebhookRoute = ApiLivekitWebhookRouteImport.update({
  id: '/api/livekit/webhook',
  path: '/api/livekit/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPortalRoute = ApiBillingPortalRouteImport.update({
  id: '/api/billing/portal',
  path: '/api/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAssistantRoute = ApiAiAssistantRouteImport.update({
  id: '/api/ai/assistant',
  path: '/api/ai/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSpacesSpaceIdRoute = AuthedSpacesSpaceIdRouteImport.update({
  id: '/spaces/$spaceId',
  path: '/spaces/$spaceId',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/spaces/$spaceId.lazy').then((d) => d.Route),
)
const AuthedDashboardCodeRoute = AuthedDashboardCodeRouteImport.update({
  id: '/dashboard/$code',
  path: '/dashboard/$code',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/dashboard/$code.lazy').then((d) => d.Route),
)
const ApiAuthCallbackGoogleLinkRoute =
  ApiAuthCallbackGoogleLinkRouteImport.update({
    id: '/api/auth/callback/google-link',
    path: '/api/auth/callback/google-link',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthCallbackGoogleRoute = ApiAuthCallbackGoogleRouteImport.update({
  id: '/api/auth/callback/google',
  path: '/api/auth/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/auth': typeof AuthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recorder': typeof RecorderRoute
  '/refund': typeof RefundRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/api/llms.json': typeof ApiLlmsDotjsonRoute
  '/api/wiki': typeof ApiWikiRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/$code': typeof AuthedDashboardCodeRoute
  '/spaces/$spaceId': typeof AuthedSpacesSpaceIdRoute
  '/api/ai/assistant': typeof ApiAiAssistantRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/livekit/webhook': typeof ApiLivekitWebhookRoute
  '/api/meetings/leave': typeof ApiMeetingsLeaveRoute
  '/api/wb-assets/$': typeof ApiWbAssetsSplatRoute
  '/api/whiteboard/pdf-upload': typeof ApiWhiteboardPdfUploadRoute
  '/api/whiteboard/snapshot': typeof ApiWhiteboardSnapshotRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/spaces/': typeof AuthedSpacesIndexRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/auth/callback/google-link': typeof ApiAuthCallbackGoogleLinkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/auth': typeof AuthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recorder': typeof RecorderRoute
  '/refund': typeof RefundRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/api/llms.json': typeof ApiLlmsDotjsonRoute
  '/api/wiki': typeof ApiWikiRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/$code': typeof AuthedDashboardCodeRoute
  '/spaces/$spaceId': typeof AuthedSpacesSpaceIdRoute
  '/api/ai/assistant': typeof ApiAiAssistantRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/livekit/webhook': typeof ApiLivekitWebhookRoute
  '/api/meetings/leave': typeof ApiMeetingsLeaveRoute
  '/api/wb-assets/$': typeof ApiWbAssetsSplatRoute
  '/api/whiteboard/pdf-upload': typeof ApiWhiteboardPdfUploadRoute
  '/api/whiteboard/snapshot': typeof ApiWhiteboardSnapshotRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/spaces': typeof AuthedSpacesIndexRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/auth/callback/google-link': typeof ApiAuthCallbackGoogleLinkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/auth': typeof AuthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recorder': typeof RecorderRoute
  '/refund': typeof RefundRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/api/llms.json': typeof ApiLlmsDotjsonRoute
  '/api/wiki': typeof ApiWikiRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authed/dashboard/$code': typeof AuthedDashboardCodeRoute
  '/_authed/spaces/$spaceId': typeof AuthedSpacesSpaceIdRoute
  '/api/ai/assistant': typeof ApiAiAssistantRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/livekit/webhook': typeof ApiLivekitWebhookRoute
  '/api/meetings/leave': typeof ApiMeetingsLeaveRoute
  '/api/wb-assets/$': typeof ApiWbAssetsSplatRoute
  '/api/whiteboard/pdf-upload': typeof ApiWhiteboardPdfUploadRoute
  '/api/whiteboard/snapshot': typeof ApiWhiteboardSnapshotRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/spaces/': typeof AuthedSpacesIndexRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/auth/callback/google-link': typeof ApiAuthCallbackGoogleLinkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$code'
    | '/auth'
    | '/llms.txt'
    | '/pricing'
    | '/privacy'
    | '/recorder'
    | '/refund'
    | '/status'
    | '/terms'
    | '/verify'
    | '/api/llms.json'
    | '/api/wiki'
    | '/invite/$token'
    | '/dashboard/$code'
    | '/spaces/$spaceId'
    | '/api/ai/assistant'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/webhook'
    | '/api/livekit/webhook'
    | '/api/meetings/leave'
    | '/api/wb-assets/$'
    | '/api/whiteboard/pdf-upload'
    | '/api/whiteboard/snapshot'
    | '/dashboard/'
    | '/settings/'
    | '/spaces/'
    | '/api/auth/callback/google'
    | '/api/auth/callback/google-link'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$code'
    | '/auth'
    | '/llms.txt'
    | '/pricing'
    | '/privacy'
    | '/recorder'
    | '/refund'
    | '/status'
    | '/terms'
    | '/verify'
    | '/api/llms.json'
    | '/api/wiki'
    | '/invite/$token'
    | '/dashboard/$code'
    | '/spaces/$spaceId'
    | '/api/ai/assistant'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/webhook'
    | '/api/livekit/webhook'
    | '/api/meetings/leave'
    | '/api/wb-assets/$'
    | '/api/whiteboard/pdf-upload'
    | '/api/whiteboard/snapshot'
    | '/dashboard'
    | '/settings'
    | '/spaces'
    | '/api/auth/callback/google'
    | '/api/auth/callback/google-link'
  id:
    | '__root__'
    | '/'
    | '/$code'
    | '/_authed'
    | '/auth'
    | '/llms.txt'
    | '/pricing'
    | '/privacy'
    | '/recorder'
    | '/refund'
    | '/status'
    | '/terms'
    | '/verify'
    | '/api/llms.json'
    | '/api/wiki'
    | '/invite/$token'
    | '/_authed/dashboard/$code'
    | '/_authed/spaces/$spaceId'
    | '/api/ai/assistant'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/webhook'
    | '/api/livekit/webhook'
    | '/api/meetings/leave'
    | '/api/wb-assets/$'
    | '/api/whiteboard/pdf-upload'
    | '/api/whiteboard/snapshot'
    | '/_authed/dashboard/'
    | '/_authed/settings/'
    | '/_authed/spaces/'
    | '/api/auth/callback/google'
    | '/api/auth/callback/google-link'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeRoute: typeof CodeRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthRoute: typeof AuthRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RecorderRoute: typeof RecorderRoute
  RefundRoute: typeof RefundRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRoute
  ApiLlmsDotjsonRoute: typeof ApiLlmsDotjsonRoute
  ApiWikiRoute: typeof ApiWikiRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiAiAssistantRoute: typeof ApiAiAssistantRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingPortalRoute: typeof ApiBillingPortalRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiLivekitWebhookRoute: typeof ApiLivekitWebhookRoute
  ApiMeetingsLeaveRoute: typeof ApiMeetingsLeaveRoute
  ApiWbAssetsSplatRoute: typeof ApiWbAssetsSplatRoute
  ApiWhiteboardPdfUploadRoute: typeof ApiWhiteboardPdfUploadRoute
  ApiWhiteboardSnapshotRoute: typeof ApiWhiteboardSnapshotRoute
  ApiAuthCallbackGoogleRoute: typeof ApiAuthCallbackGoogleRoute
  ApiAuthCallbackGoogleLinkRoute: typeof ApiAuthCallbackGoogleLinkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recorder': {
      id: '/recorder'
      path: '/recorder'
      fullPath: '/recorder'
      preLoaderRoute: typeof RecorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$code': {
      id: '/$code'
      path: '/$code'
      fullPath: '/$code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wiki': {
      id: '/api/wiki'
      path: '/api/wiki'
      fullPath: '/api/wiki'
      preLoaderRoute: typeof ApiWikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llms.json': {
      id: '/api/llms.json'
      path: '/api/llms.json'
      fullPath: '/api/llms.json'
      preLoaderRoute: typeof ApiLlmsDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/spaces/': {
      id: '/_authed/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof AuthedSpacesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/whiteboard/snapshot': {
      id: '/api/whiteboard/snapshot'
      path: '/api/whiteboard/snapshot'
      fullPath: '/api/whiteboard/snapshot'
      preLoaderRoute: typeof ApiWhiteboardSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whiteboard/pdf-upload': {
      id: '/api/whiteboard/pdf-upload'
      path: '/api/whiteboard/pdf-upload'
      fullPath: '/api/whiteboard/pdf-upload'
      preLoaderRoute: typeof ApiWhiteboardPdfUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wb-assets/$': {
      id: '/api/wb-assets/$'
      path: '/api/wb-assets/$'
      fullPath: '/api/wb-assets/$'
      preLoaderRoute: typeof ApiWbAssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/leave': {
      id: '/api/meetings/leave'
      path: '/api/meetings/leave'
      fullPath: '/api/meetings/leave'
      preLoaderRoute: typeof ApiMeetingsLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/livekit/webhook': {
      id: '/api/livekit/webhook'
      path: '/api/livekit/webhook'
      fullPath: '/api/livekit/webhook'
      preLoaderRoute: typeof ApiLivekitWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/portal': {
      id: '/api/billing/portal'
      path: '/api/billing/portal'
      fullPath: '/api/billing/portal'
      preLoaderRoute: typeof ApiBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/assistant': {
      id: '/api/ai/assistant'
      path: '/api/ai/assistant'
      fullPath: '/api/ai/assistant'
      preLoaderRoute: typeof ApiAiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/spaces/$spaceId': {
      id: '/_authed/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof AuthedSpacesSpaceIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/$code': {
      id: '/_authed/dashboard/$code'
      path: '/dashboard/$code'
      fullPath: '/dashboard/$code'
      preLoaderRoute: typeof AuthedDashboardCodeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/callback/google-link': {
      id: '/api/auth/callback/google-link'
      path: '/api/auth/callback/google-link'
      fullPath: '/api/auth/callback/google-link'
      preLoaderRoute: typeof ApiAuthCallbackGoogleLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/google': {
      id: '/api/auth/callback/google'
      path: '/api/auth/callback/google'
      fullPath: '/api/auth/callback/google'
      preLoaderRoute: typeof ApiAuthCallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardCodeRoute: typeof AuthedDashboardCodeRoute
  AuthedSpacesSpaceIdRoute: typeof AuthedSpacesSpaceIdRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedSpacesIndexRoute: typeof AuthedSpacesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardCodeRoute: AuthedDashboardCodeRoute,
  AuthedSpacesSpaceIdRoute: AuthedSpacesSpaceIdRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedSpacesIndexRoute: AuthedSpacesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeRoute: CodeRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthRoute: AuthRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RecorderRoute: RecorderRoute,
  RefundRoute: RefundRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRoute,
  ApiLlmsDotjsonRoute: ApiLlmsDotjsonRoute,
  ApiWikiRoute: ApiWikiRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiAiAssistantRoute: ApiAiAssistantRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingPortalRoute: ApiBillingPortalRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiLivekitWebhookRoute: ApiLivekitWebhookRoute,
  ApiMeetingsLeaveRoute: ApiMeetingsLeaveRoute,
  ApiWbAssetsSplatRoute: ApiWbAssetsSplatRoute,
  ApiWhiteboardPdfUploadRoute: ApiWhiteboardPdfUploadRoute,
  ApiWhiteboardSnapshotRoute: ApiWhiteboardSnapshotRoute,
  ApiAuthCallbackGoogleRoute: ApiAuthCallbackGoogleRoute,
  ApiAuthCallbackGoogleLinkRoute: ApiAuthCallbackGoogleLinkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
